import type { OficioTemplate } from './types';

export const OFICIOS_TEMPLATES: OficioTemplate[] = [
  {
    id: 'acceso_obra',
    titulo: 'Solicitud de Acceso y Permisos de Trabajo',
    categoria: 'Operativa de Obra',
    icono: 'Key',
    descripcion: 'Solicitud formal para ingreso de cuadrillas de instalación, herramientas y maniobras en alturas.',
    asuntoDefault: 'SOLICITUD DE ACCESO A INSTALACIONES Y PERMISO DE TRABAJOS EN ALTURAS',
    vocativoDefault: 'Por medio de la presente me dirijo a usted de la manera más atenta con la finalidad de solicitar:',
    antecedentesDefault: 'En seguimiento al contrato y programa de obra convenido para el suministro e instalación del sistema fotovoltaico en las instalaciones del proyecto de referencia.',
    cuerpoDefault: 'Hago de su conocimiento que a partir de la fecha indicada, la cuadrilla técnica especializada de ESOL ENERGIAS llevará a cabo los trabajos de montaje mecánico de estructuras, tendido de canalizaciones y cableado en azotea.\n\nPara tal efecto, el personal asignado cuenta con equipo de protección personal (EPP) completo, arneses de seguridad normados y certificación DC-3 para trabajos en alturas y riesgo eléctrico.',
    fundamentacionDefault: 'Con base en las normas oficiales NOM-009-STPS-2011 (Trabajo en alturas) y NOM-029-STPS-2011 (Mantenimiento de instalaciones eléctricas en los centros de trabajo).',
    peticionDefault: '1. Autorización de acceso peatonal y vehicular para el personal y vehículos de carga.\n2. Habilitación de toma de corriente provisional y área designada para resguardo temporal de herramienta.',
    despedidaDefault: 'Agradeciendo de antemano su valioso apoyo y colaboración para el adecuado desarrollo de los trabajos, quedo a sus respetables órdenes.',
    ccpDefault: ['Supervisión de Seguridad e Higiene', 'Residencia de Obra', 'Archivo de Proyecto'],
    anexosDefault: ['Lista de personal y números de afiliación IMSS (SUA)', 'Formatos DC-3 vigentes', 'Matriz de identificación de riesgos']
  },
  {
    id: 'solicitud_libranza_cfe',
    titulo: 'Solicitud de Libranza / Corte Programado',
    categoria: 'CFE / Media Tensión',
    icono: 'Zap',
    descripcion: 'Gestión técnica y solicitud de desenergización temporal para interconexión a tablero general o subestación.',
    asuntoDefault: 'SOLICITUD DE LIBRANZA ELÉCTRICA Y CORTE PROGRAMADO PARA INTERCONEXIÓN',
    vocativoDefault: 'Estimado(a) Superintendente / Administrador de Inmueble: Por medio del presente conducto me dirijo a usted para solicitar:',
    antecedentesDefault: 'Habiendo concluido la etapa de montaje físico de módulos fotovoltaicos, inversores y tableros de acoplamiento conforme al proyecto de ingeniería aprobado.',
    cuerpoDefault: 'Es técnicamente indispensable realizar la conexión final en el bus de barras del Tablero General de Distribución (TGD) y pruebas de sincronización. Para garantizar la seguridad del personal y la integridad de las instalaciones eléctricas del inmueble, me permito solicitar programar una libranza temporal del suministro eléctrico en la fecha y horario propuestos.',
    fundamentacionDefault: 'Conforme a la NOM-001-SEDE-2012 (Artículos 690 y 705) y las especificaciones técnicas de CFE Distribución para Generación Distribuida.',
    peticionDefault: '1. Autorización de ventana de libranza de 4 horas para realizar el acoplamiento y pruebas dieléctricas.\n2. Coordinación con el personal de mantenimiento interno para la maniobra de apertura y cierre de interruptores.',
    despedidaDefault: 'Sin otro particular por el momento y agradeciendo su pronta respuesta para evitar demoras en la puesta en marcha, quedo a su entera disposición.',
    ccpDefault: ['Jefatura de Mantenimiento', 'Agencia Comercial / CFE Distribución', 'Archivo ESOL Energias'],
    anexosDefault: ['Diagrama Unifilar de Interconexión', 'Procedimiento seguro de libranza y bloqueo (LOTO)']
  },
  {
    id: 'suspension_atraso',
    titulo: 'Notificación de Suspensión / Atraso por Terceros',
    categoria: 'Blindaje Legal y Contractual',
    icono: 'AlertTriangle',
    descripcion: 'Notificación formal de suspensión temporal o atraso imputable a causas ajenas, lluvias o falta de suministros del cliente.',
    asuntoDefault: 'NOTIFICACIÓN DE SUSPENSIÓN TEMPORAL DE ACTIVIDADES POR CAUSAS AJENAS A NUESTRA EMPRESA',
    vocativoDefault: 'Por medio del presente conducto, me dirijo a usted con la debida formalidad para hacer constar lo siguiente:',
    antecedentesDefault: 'En relación con el programa de ejecución de obra y los compromisos contractuales establecidos para el proyecto.',
    cuerpoDefault: 'Hago constar de manera formal que el día de hoy nos vemos en la imperiosa necesidad de suspender temporalmente las actividades de instalación debido a causas de fuerza mayor / falta de liberación de áreas / corte imprevisto de suministro / atraso en obra civil a cargo de terceros.\n\nEsta situación imposibilita el avance continuo y seguro de nuestros técnicos conforme al cronograma acordado.',
    fundamentacionDefault: 'De conformidad con las cláusulas de Fuerza Mayor y Responsabilidad del Contrato de Prestación de Servicios, así como las disposiciones aplicables del Código Civil.',
    peticionDefault: '1. Tomar debida nota de la fecha de inicio de la suspensión para la debida reprogramación y ajuste del calendario de entrega sin penalización para ESOL ENERGIAS.\n2. Agendar reunión urgente para definir la fecha de liberación del área y reinicio de labores.',
    despedidaDefault: 'Reiterando mi compromiso con la calidad y cumplimiento del proyecto una vez subsanadas las condiciones mencionadas, quedo atento a sus instrucciones.',
    ccpDefault: ['Dirección de Proyecto', 'Supervisión Externa', 'Departamento Jurídico'],
    anexosDefault: ['Bitácora fotográfica de impedimento de trabajo', 'Reporte de condiciones de sitio']
  },
  {
    id: 'prorroga',
    titulo: 'Solicitud de Prórroga Justificada',
    categoria: 'Control de Tiempos',
    icono: 'Calendar',
    descripcion: 'Petición formal y justificada de extensión de plazo de entrega por modificaciones o trámites de dependencias.',
    asuntoDefault: 'SOLICITUD DE PRÓRROGA AL PLAZO DE ENTREGA DE OBRA',
    vocativoDefault: 'Estimados miembros del Comité de Obra / Supervisión: Por medio de la presente me dirijo a ustedes para solicitar:',
    antecedentesDefault: 'Haciendo referencia al contrato de obra vigente y a los eventos extraordinarios suscitados durante el periodo de ejecución.',
    cuerpoDefault: 'Por medio de la presente, solicito formalmente una prórroga de días naturales al plazo de entrega contractual del proyecto de referencia. Dicha solicitud se encuentra plenamente justificada en virtud de los tiempos de dictamen ante Unidad de Verificación (UVIE) / retrasos meteorológicos extraordinarios / adecuaciones estructurales solicitadas por el cliente.',
    fundamentacionDefault: 'Sustentado en las minutas de obra levantadas previamente y en apego a los términos contractuales que rigen la relación entre las partes.',
    peticionDefault: '1. Formalizar la nueva fecha compromiso de entrega-recepción mediante adendum al contrato.\n2. Convalidar el nuevo programa de pruebas y energización.',
    despedidaDefault: 'Agradeciendo de antemano su comprensión y aprobación para concluir los trabajos con los más altos estándares de calidad y seguridad, quedo a sus respetables órdenes.',
    ccpDefault: ['Residencia de Obra', 'Administración General', 'Archivo'],
    anexosDefault: ['Cronograma de obra reprogramado', 'Minutas de obra y reportes de lluvia/trámite']
  },
  {
    id: 'adicionales_modificacion',
    titulo: 'Notificación de Trabajos Extraordinarios / Adicionales',
    categoria: 'Costos y Alcances',
    icono: 'FilePlus',
    descripcion: 'Presentación formal de volúmenes excedentes, obras adicionales y solicitud de autorización de presupuesto complementario.',
    asuntoDefault: 'NOTIFICACIÓN DE TRABAJOS EXTRAORDINARIOS Y SOLICITUD DE AUTORIZACIÓN',
    vocativoDefault: 'Por medio del presente oficio me dirijo a usted para presentar:',
    antecedentesDefault: 'Durante la etapa de ejecución e inspección en sitio de la infraestructura eléctrica existente.',
    cuerpoDefault: 'Se detectó la necesidad de ejecutar conceptos no previstos en el catálogo original (adecuación de canalizaciones, refuerzo estructural en cubierta, instalación de apartarrayos de media tensión) indispensables para garantizar la seguridad operativa y el cumplimiento de la NOM-001-SEDE-2012.\n\nDichos trabajos representan un alcance complementario necesario antes del cierre definitivo de la obra.',
    fundamentacionDefault: 'NOM-001-SEDE-2012 y especificaciones de seguridad industrial aplicables.',
    peticionDefault: '1. Revisión y firma de autorización del presupuesto complementario anexo.\n2. Autorización por escrito para proceder con la ejecución de los conceptos extraordinarios.',
    despedidaDefault: 'Quedo a su disposición para cualquier aclaración técnica respecto a los conceptos y volúmenes presentados.',
    ccpDefault: ['Supervisión Técnica', 'Control de Presupuestos', 'Archivo'],
    anexosDefault: ['Presupuesto desglosado de trabajos extraordinarios', 'Evidencia fotográfica y dictamen técnico']
  },
  {
    id: 'entrega_recepcion',
    titulo: 'Entrega y Recepción de Obra / Finiquito',
    categoria: 'Cierre y Protocolo',
    icono: 'CheckCircle2',
    descripcion: 'Oficio formal de conclusión satisfactoria de trabajos, solicitud de inspección final y firma de acta de entrega.',
    asuntoDefault: 'NOTIFICACIÓN DE CONCLUSIÓN DE TRABAJOS Y SOLICITUD DE ACTA ENTREGA-RECEPCIÓN',
    vocativoDefault: 'Estimado(a) Cliente y Supervisión: Me es muy grato dirigirme a usted para hacer de su conocimiento que:',
    antecedentesDefault: 'En cumplimiento total del alcance estipulado en la cotización y contrato de instalación fotovoltaica.',
    cuerpoDefault: 'Me es muy grato informarle que los trabajos de suministro, instalación electromecánica, interconexión, parametrización y pruebas de funcionamiento del sistema solar han concluido satisfactoriamente al 100%.\n\nEl sistema se encuentra operando bajo condiciones óptimas y produciendo energía limpia en estricto cumplimiento de los parámetros de diseño.',
    fundamentacionDefault: 'Cumplimiento cabal de las especificaciones contractuales, NOM-001-SEDE-2012 y pruebas de puesta en servicio.',
    peticionDefault: '1. Realizar el recorrido conjunto de inspección final en la fecha que tenga a bien designar.\n2. Proceder a la firma del Acta Entrega-Recepción física y administrativa de la obra.',
    despedidaDefault: 'Agradeciendo la confianza depositada en ESOL ENERGIAS para la realización de su proyecto energético, me reitero a sus muy distinguidas órdenes.',
    ccpDefault: ['Gerencia Técnica', 'Departamento de Garantías y Pólizas', 'Archivo'],
    anexosDefault: ['Reporte de pruebas y puesta en marcha', 'Dossier de calidad y hojas de datos de equipos']
  },
  {
    id: 'requerimiento_tecnico',
    titulo: 'Requerimiento Técnico / Trámite UVIE / CFE',
    categoria: 'Gestoría y Trámites',
    icono: 'FileText',
    descripcion: 'Solicitud formal de recibos CFE, firmas de cartas poder o datos del predio necesarios para el expediente oficial.',
    asuntoDefault: 'REQUERIMIENTO DE DOCUMENTACIÓN PARA TRÁMITE DE INTERCONEXIÓN ANTE CFE',
    vocativoDefault: 'Por medio de la presente, solicito de su amable apoyo con lo siguiente:',
    antecedentesDefault: 'Con el objetivo de ingresar oportunamente la solicitud de contrato de interconexión ante CFE Suministrador de Servicios Básicos.',
    cuerpoDefault: 'Se requiere completar la documentación oficial del titular del contrato para la integración del expediente técnico.\n\nLa falta de entrega oportuna de dichos documentos suspende el cómputo de los plazos de respuesta de la paraestatal para el cambio de medidor bidireccional.',
    fundamentacionDefault: 'Manual Regulatorio de Coordinación de la CRE y Disposiciones Administrativas de Carácter General para Generación Distribuida.',
    peticionDefault: '1. Envío de copia del último recibo CFE pagado (ambos lados en PDF legible).\n2. Copia de identificación oficial (INE) y Constancia de Situación Fiscal actualizada del titular.',
    despedidaDefault: 'Agradeciendo de antemano el envío de los documentos para evitar demoras en su trámite de interconexión, quedo a sus respetables órdenes.',
    ccpDefault: ['Área de Gestoría CFE', 'Archivo de Proyecto'],
    anexosDefault: ['Formato de Solicitud de Interconexión CFE prellenado']
  },
  {
    id: 'libre',
    titulo: 'Oficio Libre / Redactor Libre con IA',
    categoria: 'General y Personalizado',
    icono: 'Sparkles',
    descripcion: 'Crea un oficio a la medida para cualquier situación técnica, administrativa o legal apoyado con Inteligencia Artificial.',
    asuntoDefault: 'ASUNTO: COMUNICADO OFICIAL DE OBRA',
    vocativoDefault: 'Por medio de la presente me dirijo a usted de la manera más atenta para exponer:',
    antecedentesDefault: '',
    cuerpoDefault: 'Por medio del presente oficio me dirijo a usted con la debida atención para exponer los siguientes hechos y consideraciones relativas a la obra de referencia...',
    fundamentacionDefault: '',
    peticionDefault: '',
    despedidaDefault: 'Sin otro particular por el momento, quedo a sus respetables órdenes para cualquier duda o comentario.',
    ccpDefault: ['Archivo'],
    anexosDefault: []
  }
];
